### ISSUE TITLE
Indikator Ada Pesan Belum Dibaca

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-flutter#109]
1. Pada Navbar bawah, menu Pesan diberi tanda jika ada pesan belum dibaca.
2. Di halaman daftar pesan, diberikan indikator/warna yang berbeda pesan belum dibaca vs sudah dibaca.
3. Tandai Semua Pesan Sudah Dibaca.

Karena di Firestore belum ada fungsi untuk menyimpan kondisi sebuah pesan sudah dibaca oleh user atau belum, maka logic ini dilakukan di mobile app. Disimpan di local storage device.

**Comment by yohang88** [comment]
Ini masih bisa masuk ke release kita malam ini ga ya @gaganugraha33 ?

**Comment by gaganugraha33** [comment]
- [ ] Pesan tandai jika belum dibaca
- [ ] Indikator pesan belum dibaca
- [ ] Tandai semua sudah dibaca
