### ISSUE TITLE
Description PIKOBAR di Play Store

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-flutter#123]
**Bahasa Indonesia**
Pusat Informasi dan Koordinasi Wabah Penyakit dan Bencana Jawa Barat atau PIKOBAR Jabar ini kami kembangkan agar warga Jabar dapat mengakses data dan statistic terbaru di Jawa Barat, mengajukan kebutuhan logistik, mengakses nomer-nomer darurat, membaca klarifikasi berita-berita hoaks, dll.

Wargi bisa bantu pemerintah dengan memberikan aspirasi dengan mengisi survey dan dengan berdonasi, baik bantuan tunai maupun logistik. 

**Bahasa Inggris**
The Information and Coordination Centre for Disease and Disaster in West Java (PIKOBAR) has been set up to allow West Java citizens to have a quicker and easier access to the latest data and statistics in West Java, to submit proposals for logistical needs, to access emergency numbers, to read clarifications on misinformation (fake messages and unfounded rumors), et cetera. 

The West Java citizens can support the government by filling out surveys to help goverment monitor ground-up data and by donating in-kind and/or financial supports for those in dire needs.

**Comment by yohang88** [comment]
Ini dari Dyana kan? Sudah diganti kok. Mas @adtrimurdani , tinggal nunggu proses review dari Google.
