### ISSUE TITLE
Web view fitur Forum

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-flutter#132]
Sesuai kesepatan yang dibahas di Slack, Forum menggunakan 3rd party (referensi pakai Discourse atau Flarum).

Btw, untuk kedua 3rd party di atas, apakah butuh explore dulu ngga? Kalo iya saya minta bantuan temen2 BA/UX untuk review kedua nya yg mana yg paling memenuhi kriteria Pikobar

**Comment by aldidoanta** [comment]
Boleh kang @adtrimurdani. Requirement-nya nggak ada perubahan kan? Minta bantuan tmn2 untuk explore:

1. Kalau pakai webview, tampilan dan performance-nya lebih bagus yang mana
2. Apakah support autentikasi dengan Google Account

**Comment by adtrimurdani** [comment]
Ok siap kang @aldidoanta kami review dulu

**Comment by yohang88** [comment]
Ini sudah bisa dicoba pakai versi APK terbaru ya, menu Forum sudah diaktifkan dan sementara tercepat pakai Discourse. Feedbacknya ditunggu yes.

**Comment by adtrimurdani** [comment]
Eh iya maap2 ga keliatan kalo menu "Forum" sudah aktif mas @yohang88 kang @aldidoanta.
Mantap, siap di tes2 dulu. Nuhuns

**Comment by yohang88** [comment]
-1 Google Sign In tidak jalan di embed webview

**Comment by yohang88** [comment]
Ini solusinya salah satunya khusus menu Forum, diganti Chrome Custom Tab cc: @anandarh @alchemistt99

**Comment by anandarh** [comment]
Untuk issue ini sudah aman kah untuk di close? @yohang88 @adtrimurdani
