### ISSUE TITLE
Fitur Cek Sebaran

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-flutter#133]
Desain: http://bit.ly/Pikobar-Mobile

Menu widget Cek Sebaran di homescreen sudah OK
![image](https://user-images.githubusercontent.com/61811037/77845588-4f920400-71da-11ea-80e0-911be50d4437.png)
![image](https://user-images.githubusercontent.com/61811037/77845598-5c165c80-71da-11ea-93e7-1a0f507a278c.png)

Selanjutnya untuk fitur Cek Sebarannya sesuai design Figma, apakah akan menggunakan webview atau native? Karena value dari fitur ini lumayan tinggi (akan banyak user terbantu dgn fitur ini), minta masukkannya untuk development yang paling possible yang mana 🙏

**Comment by yohang88** [comment]
Mas @adtrimurdani awalnya saya pikir webview. Tapi melihat sumber daya tim mobile dev yang lebih banyak kosong, nampaknya kita bikin native/flutter aja. 

Cons-nya jika native/flutter adalah untuk rilis update jika ada perubahan, ga bisa sering-sering (proses approval review dari google play store yang lama).

**Comment by adtrimurdani** [comment]
Ok mas @yohang88 kalau yang paling possible native/flutter, nanti di sisi testing kita lebih detailkan lagi biar minim revisi

**Comment by alchemistt99** [comment]
@aldidoanta apakah sudah ready collections nya ?

**Comment by aldidoanta** [comment]
@alchemistt99 Boleh minta usulan struktur collection-nya? Maap lagi riweuh :sob:

**Comment by alchemistt99** [comment]
owalah yaudah lanjut aja dulu do @aldidoanta urusan nya :smiley:

**Comment by yohang88** [comment]
@aldidoanta @alchemistt99 Ha? Ini harusnya ga ada firestore, karena checkingnya langsung ke API.

Wait, API-nya sudah dibuat data engineer.

**Comment by aldidoanta** [comment]
> @aldidoanta @alchemistt99 Ha? Ini harusnya ga ada firestore, karena checkingnya langsung ke API.
> 
> Wait, API-nya sudah dibuat data engineer.

Oh yang public API itu mas? sipsip
