### ISSUE TITLE
Input kode verifikasi SMS tidak terlihat di layar

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-flutter#134]
Edit profile > pas input kode sms, kode nya tidak terlihat, tapi berhasil disubmit
![image](https://user-images.githubusercontent.com/61811037/77846108-cb418000-71dd-11ea-8047-330012665ad5.png)
Apakah memang begitu tampilannya?

**Comment by aldidoanta** [comment]
Kalau di kang @adtrimurdani OTP-nya harus diketik manual, nggak otomatis?

**Comment by jaluowen** [comment]
Pas diinput angkanya ga keliatan kang @adtrimurdani ?

**Comment by adtrimurdani** [comment]
Kebetulan saya nyobain pake nomor yg SIM nya ga installed di HP saya kang @aldidoanta , jdi input manual. Klo pake nomor saya sendiri mah keinput otomatis.

Iya betul kang @jaluowen pas input kodenya ga keliatan

**Comment by yohang88** [comment]
Sip ini sekalian nyambung issue #130 yes.

**Comment by yohang88** [comment]
@jaluowen UX setelah nomor tersimpan, dibalikin ke halaman view profile aja. Kalau tetap di halaman edit screen, takutnya berulang kali klik Simpan. Dan itu terjadi pada saya. Haha.

**Comment by jaluowen** [comment]
siap mas @yohang88
