### ISSUE TITLE
Fail Debugging

### ISSUE THREAD

**Issue by hariansyahhari2** [jabardigitalservice/pikobar-flutter#135]
Sebelumnya mohon izin bergabung di team ini. Setelah saya clone repository ini dan melakukan run setelah melakukan "flutter pub get" muncul error seperti ini
![image](https://user-images.githubusercontent.com/54599354/77858157-dfac6980-722b-11ea-9c2d-f052ded74f79.png)

Mohon bimbingannya, saya belum terlalu terbiasa menggunakan flutter karena sebelumnya saya menggunakan react native hehehe

**Comment by maasdi** [comment]
@hariansyahhari2 kamu harus setup project di firebase console. https://console.firebase.google.com.
Kemudian download google-services.json ke folder android\app.

Di project ini, kita pake remote config, firestore dan beberapa firebase feature yang perlu enable.

**Comment by aldidoanta** [comment]
Iya, untuk saat ini setiap developer harus membuat Firebase project sendiri-sendiri. Saat ini belum ada solusi untuk menjalankan Firebase di local machine tanpa harus membuat Firebase project.

Referensi issue: https://github.com/jabardigitalservice/pikobar-jabarprov-go-id/issues/56

**Comment by hariansyahhari2** [comment]
@maasdi @aldidoanta Saya kira firebasenya pakai akun milik bersama. Okee kalo begitu saya mau set up dulu. Terimakasih kang

**Comment by anandarh** [comment]
Ini sudah solved ya,, issuenya saya tutup.
