### ISSUE TITLE
Record personal FCM registration token

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-flutter#138]
Saat ini setiap devices subscribe topic "general" untuk FCM. 

Perlu ditambahkan record registration token per user yang sudah login. Sehingga kita bisa mengirim push notif yang targetted ke user/registration token tertentu.

Token FCM bisa disimpan di collection `users/{userId}/tokens/{token}`.  Tiap token bisa ditambahkan atribut `created_at` (tanggal token disimpan).

**Comment by maasdi** [comment]
Ini mau register tokennya kapan?

Untuk user baru mungkin bisa setelah login, 
tapi untuk yang sudah login pilihannya di check saat app launch. const-nya harus check sudah register atau belum.

**Comment by yohang88** [comment]
> Ini mau register tokennya kapan?
> 
> Untuk user baru mungkin bisa setelah login,
> tapi untuk yang sudah login pilihannya di check saat app launch. const-nya harus check sudah register atau belum.

Kalau saya terpikirkannya pada saat login mas @maasdi . Sehingga bisa ter-record di Firestore di collections `users/{userId}/tokens/{token}`. Ada masukan lain mas?

**Comment by maasdi** [comment]
Kang @yohang88  setuju untuk di record ketika login berhasil.

Untuk app yg sudah terlebih dahulu dirilis seperti Pikobar, kadang kadang ada concern gimana untuk existing user yang sudah login, artinya gak akan ter-record tokennya.

**Comment by anandarh** [comment]
Untuk fitur login ini masih baru akan dirilis kang @maasdi, di Pikobar yg sekarang sudah rilis di playstore belum ada fitur loginnya. Jadi masih aman untuk record FCM tokennya.

**Comment by maasdi** [comment]
@anandarh I see.
Jadi gak perlu special handling, bagus bagus!

**Comment by anandarh** [comment]
Sip. Issue ini berati sudah aman ya bisa di close. Atau mungkin ada masukan lain kang @maasdi ?

**Comment by maasdi** [comment]
Hahaha aman dan bisa di close

**Comment by anandarh** [comment]
Siap nuhun kang @maasdi
