### ISSUE TITLE
Broken image bagian dukungan

### ISSUE THREAD

**Issue by dhiemaz** [jabardigitalservice/pikobar-flutter#142]
Terdapat broken pada halaman - halaman yang mempunyai bagian dukungan (didukung oleh).

**Comment by denisenricohasyim93** [comment]
> Terdapat broken pada halaman - halaman yang mempunyai bagian dukungan (didukung oleh).

brader @dhiemaz ... boleh screenshot evidence nya ? punten ... nuhun ...

**Comment by dhiemaz** [comment]
![Screenshot_2020_0401_084757](https://user-images.githubusercontent.com/6150781/78091863-51d1a980-73f8-11ea-8013-727bb7eb7312.png)
![Screenshot_2020_0401_090508](https://user-images.githubusercontent.com/6150781/78091867-54340380-73f8-11ea-8c70-61d82f35f724.png)

Terlampir screenshotnya ya.. cek kondisi koneksi internet sih aman damai..

**Comment by aldidoanta** [comment]
Hatur nuhun kang @dhiemaz @denisenricohasyim93 (hey, long time no see!) untuk laporannya. Created a hotfix to resolve this issue https://github.com/jabardigitalservice/pikobar-jabarprov-go-id/pull/77
