### ISSUE TITLE
Mengganti implementasi Webview ke Custom Chrome Tab

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-flutter#145]
Webview ini ada beberapa issues (cmiiw):
1. Lag
2. Tidak bisa login dengan Google Sign In (error: forbidden user agent)
3. Beberapa web yang ada select element, force close.

Untuk ini nampaknya perlu diganti implementasinya jadi Custom Chrome Tab, dengan cons:
1. Jika tidak terinstall Chrome di device, akan dilempar ke browser lain (UX-nya jadi terpisah aplikasi).

Webview yang perlu diganti:
1.  Banner on-tap
2. Home announcement on-tap
3. Data Jabar
4. Data Nasional
5. Data Dunia
6. Donasi
7. Daftar Relawan
8. Lapor Kasus
9. Forum
10. Logistik
12. Lapor Kasus

Jika ada opsi / diskusi silahkan.

**Tambahan**
Jika user dalam kondisi SUDAH LOGIN di PIKOBAR, URL-nya ditambahkan query params sebagai berikut:
```
https://forum.pikobar.jabarprov.go.id?uid={firebase_uid}
```
Pastikan URL-nya encoded URL safe, misal spasi digantikan karakter `%20`.

**Comment by anandarh** [comment]
Gas, seragamkan saja Custom Chrome Tab.

**Comment by yohang88** [comment]
> Gas, seragamkan saja Custom Chrome Tab.

Boleh mas bram

**Comment by anandarh** [comment]
@yohang88 Btw, itu parameter di urlnya mau polosan aja? Kalo pake Custom Chrome Tab bakal bisa keliatan semua dong.

**Comment by yohang88** [comment]
> @yohang88 Btw, itu parameter di urlnya mau polosan aja? Kalo pake Custom Chrome Tab bakal bisa keliatan semua dong.

**Comment by yohang88** [comment]
zzzz kepencet

ada issue jika keliatahan @anandarh ?

**Comment by anandarh** [comment]
Cuma terasa terlalu polos dan privasinya terlalu terbuka aja sih.

**Comment by yohang88** [comment]
Woke sepakat, updated cukup `uid` saja ya @anandarh .

Nanti kalau web/didalamnya ingin dapat user, bisa request ke API terpisah.
