### ISSUE TITLE
Penambahan field baru di Edit Profile

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-flutter#154]
Field2 berikut minta ditambahkan di table `users` untuk keperluan contact tracking yang dashboard nya sedang di-develop oleh Geocreate (thread pembahasan ada di Slack):

- `gender` (mandatory, dropdown key-values jenis kelamin Male/Female)
- `birthdate` (mandatory, type timestamp/date saja, date picker, validasi tidak boleh memilih date masa depan)
- `phone_number` (mandatory, ini sudah ada ya)
- `address` (mandatory, input text string, untuk alamat domisili)
- `city_id` (mandatory, dropdown pakai master data kab/kota Jawa Barat, untuk kota domisili)
- `province_id` --> ini diisi kode Jawa Barat "32", static/hidden field saja.

**Comment by yohang88** [comment]
ini hold dulu ya, saya perlu tahu kebutuhannya untuk apa dulu.

**Comment by adtrimurdani** [comment]
Kebutuhannya untuk supply data ke dashboard Geocreate mas @yohang88

**Comment by yohang88** [comment]
OK ini jadinya sekalian aja menambahkan field isian di Edit Profile ya, mas @adtrimurdani. 

Saya izin edit judul dan deskripsi tasknya.

**Comment by jaluowen** [comment]
yang menambahkan field di tabelnya siapa ya mas? @yohang88

**Comment by yohang88** [comment]
@jaluowen harusnya ga perlu ditambahkan satu-satu, kan ini Firestore bisa dinamis ya. Asalkan form editnya jalan, akan nambah field/atributnya yang belum ada kan.

Perlu hati-hati menangani record user yang datanya masih null/belum punya field atribut yang sesuai agar tidak error.

**Comment by jaluowen** [comment]
@yohang88 oh siap mas kalo begitu

**Comment by jaluowen** [comment]
![image](https://user-images.githubusercontent.com/48124139/78757041-098d2b00-79a6-11ea-8dc1-a2d0fc9684e6.png)

@yohang88 @adtrimurdani apakah seperti ini cukup?

**Comment by yohang88** [comment]
@jaluowen field `gender`, yang disimpak key-nya ya, `M` atau `F`.

Kode kabupaten/kota, wait aku carikan daftarmya.

**Comment by jaluowen** [comment]
kode kab/kota saya pake dari api ini mas `https://covid19-public.digitalservice.id/api/v1/wilayah/jabar?level=kabupaten` @yohang88

**Comment by yohang88** [comment]
@jaluowen oke bisa sih pakai itu. Tapi pastikan dropdownnya di-sort by nama_wilayah ascending ya.

**Comment by jaluowen** [comment]
baik siap mas @yohang88

**Comment by yohang88** [comment]
Ini aku open lagi ya, catatan issue dari saya untuk latest APK:
1. Tombol Simpan tidak bagus secara UX/UI, sebaiknya ditempatkan di bagian bawah form saja.
2. Semua field mandatory, pada nama fieldnya diberi tanda bintang merah seperti pada umumnya.
3. Label Kota Domisili diganti jadi "Kabupaten/Kota Domisili"
4. Behavior validasi saat field kosong tidak konsisten yang diberi warna merah.
