### ISSUE TITLE
Memperjelas screen hasil cek sebaran kasus

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-flutter#157]
Saat ini screen feature cek sebaran kasus, hasilnya seperti ini:
![image](https://user-images.githubusercontent.com/618412/78524162-5bdf1800-77fd-11ea-8d85-f5a0cc4190cb.png)

Menurut saya ini rawan misleading, user akan bertanya ini terdekat cara hitungnya darimana? dari radius atau dari kelurahan dan kecamatan?

Kalau dari API, infonya sudah tersedia:
1. Jumlah kasus dalam radius 2 km
2. Jumlah kasus dalam 1 kelurahan
3. Jumlah kasus dalam 1 kecamatan

![image](https://user-images.githubusercontent.com/618412/78524223-892bc600-77fd-11ea-8275-2ee2f031e1dd.png)

Kalau mau, di screen tampilan cek sebaran ini ditampilkan aja semuanya, dalam bentuk tabel atau lain. Jadi ada info jumlah kasus berdasar radius, kelurahan, dan kecamatan.

**Comment by ReksaMohammad** [comment]
sudah di update ya, tolong di check dulu
cc: @yohang88 

<img width="927" alt="Screen Shot 2020-04-06 at 15 03 30" src="https://user-images.githubusercontent.com/42407562/78536355-ec2a5680-7817-11ea-9153-6da51bceb65e.png">

**Comment by adtrimurdani** [comment]
Boleh ditambahkan kata2 ini ngga mang @ReksaMohammad ? penempatannya di atas yg "Tetap tenang....":
"Titik lokasi merupakan titik acak (random by system) wilayah yang tertera pada identitas kasus dan tidak menunjuk pada alamat persis masing-masing kasus"

**Comment by yohang88** [comment]
Ini aku open lagi ya, ada catatan hasil test untuk latest APK:

1. Bagian disclaimer belum sesuai
![image](https://user-images.githubusercontent.com/618412/78851726-bc13cb00-7a44-11ea-805f-888b1a166e2e.png)

2. Bagian hasil kasus aktif di Kecamatan dan Kelurahan kotak-kotaknya bisa geser/broken/glitch. Kalau memang desainnya susah, mungkin bisa disesuaikan.
![image](https://user-images.githubusercontent.com/618412/78851764-db125d00-7a44-11ea-8e5e-7858dd6535e7.png)

3. Bagian atas, Tanggal update seperti diskusi di Slack aja, diganti jadi: 
```
Diperbarui 24 jam terakhir. Lihat Disclaimer/Penyangkalan.
```
![image](https://user-images.githubusercontent.com/618412/78851926-48be8900-7a45-11ea-8e1c-65cb57652ef6.png)

4. Radius 2km, km-nya diberi spasi didepannya.
