### ISSUE TITLE
Di screen Home, ditambahkan daftar Dokumen, Protokol, dan Download

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-flutter#159]
Sebagai user, saya bisa melihat daftar dokumen (PDF) dan download file tersebut.

Yang dibutuhkan/ditampilkan (bikin collection baru di Firestore):
1. Judul dokumen
2. Deskripsi dokumen
3. Link download file (kalau di-tap, aksinya adalah download).
4. Action share (share file, bukan share link) [nice to have]
5. Tanggal publish (sort by tanggal publish, paling baru paling atas).

Struktur collections:
![image](https://user-images.githubusercontent.com/618412/78680893-43165580-7916-11ea-9486-ae690a442ed7.png)

Ditampilkan berdasarkan `published = true` dan sort-by `published_at` descending.

**Comment by ReksaMohammad** [comment]
> Sebagai user, saya bisa melihat daftar dokumen (PDF) dan download file tersebut.
> 
> Yang dibutuhkan/ditampilkan (bikin collection baru di Firestore):
> 
> 1. Judul dokumen
> 2. Deskripsi dokumen
> 3. Link download file (kalau di-tap, aksinya adalah download).
> 4. Action share (share file, bukan share link) [nice to have]
> 5. Tanggal publish (sort by tanggal publish, paling baru paling atas).

dokumen apa ini mas?

**Comment by adtrimurdani** [comment]
Bantu jawab, bentuknya sperti info praktikal, namun formatnya PDF mang @ReksaMohammad .
Sejauh ini dokumen yg saya terima yaitu masih berhubungan dengan info2 praktikal. Mending kita satukan di menu tsb, atau ada kemungkinan lain mas @yohang88 ?

**Comment by ReksaMohammad** [comment]
nah mending di fix dulu aja, soalnya sayang aja gitu layoutnya kalo bisa di gabung ya gabung aja. Disatu sisi dari UI nya juga enak nantinya engga banyak yg kosong.

**Comment by yohang88** [comment]
Menurutku beda sih, infografis dan dokumen-dokumen kayak protokol pengurusan jenazah, dsb.

Infografis kan thumbnailnya gambar? Kalau dokumen?

**Comment by ReksaMohammad** [comment]
hooo oqe mas, dibuat di homescreen paling bawah ya? atau sebelum infografis?

**Comment by yohang88** [comment]
Eh betul desain bebas ya, tidak harus dibawahnya, betul, bisa juga pakai tabs atau yang lain.

**Comment by ReksaMohammad** [comment]
<img width="506" alt="Screen Shot 2020-04-07 at 14 02 03" src="https://user-images.githubusercontent.com/42407562/78639559-60c4ca00-78d8-11ea-8362-e85c2e32098b.png">

punten, bisa di cek dulu mas @yohang88

**Comment by yohang88** [comment]
Oke sip gaaas @ReksaMohammad

**Comment by gaganugraha33** [comment]
mang bedanya Button ijo selengkapnya sama samping tulisan Dokumen apa? @ReksaMohammad

**Comment by yohang88** [comment]
Bantu jawab,

Selengkapnya: ini seperti list berita (yang di home kan dilimit 3 items)

Button Ijo: tombol download ini harusnya. Itu berupa URL file PDF yak.

**Comment by ReksaMohammad** [comment]
sorry mas @yohang88, itu dibuat textnya biru + underline sih niatnya supaya cara downloadnya itu di tap textnya, karena engga ada detail dokumennya kan? Tambahan yang button ijo sebelah kanan itu untuk share ya supaya konsisten sama yg di atasnya @gaganugraha33

**Comment by yohang88** [comment]
Oke sepakat @ReksaMohammad 

Btw firebase collections dah aku update dengan `documents` yak @gaganugraha33 

Deskripsi task di atas aku update.

**Comment by gaganugraha33** [comment]
okeyy sheepp @ReksaMohammad @yohang88

**Comment by ReksaMohammad** [comment]
mantap soul bapak bapak kuu :))

**Comment by yohang88** [comment]
Ini latest build, catatan issue dari saya:
1. Fitur share, apakah memungkinkan yang dishare berupa file-nya, bukan link?
2. Jika nomor 1 tidak bisa, share text-nya ditambahkan Judul Dokumen, contoh:
```
PERGUB PENGURANGAN DAMPAK COVID APRIL 2020 REVISI 7 APRIL 1
Unduh dokumen: https://host/file.pdf

Dibagikan dari Pikobar
```

**Comment by gaganugraha33** [comment]
@yohang88 bisa mas, buat ekstension file nya bakal selalu pdf atau ada kemungkinan lain mas?

**Comment by adtrimurdani** [comment]
bantu jawab, selalu pdf kang @gaganugraha33

**Comment by gaganugraha33** [comment]
@adtrimurdani siapp kang
