### ISSUE TITLE
Kirim kode OTP via Whatsapp

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-flutter#162]
Saat ini kita punya Whatsapp API yang bisa digunakan untuk kirim kode OTP saat verifikasi nomor telepon. Adakah usulan bagaimana mekanisme/flownya?

**Comment by liimalim** [comment]
Bisa di cek dokumentasinya [https://wa.alim.my.id/](https://wa.alim.my.id/)
