### ISSUE TITLE
Infografis/Info Praktikal dibuat multiple images

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-flutter#168]
Collection Infografis/Info Praktikal sudah support multiple images, sehingga seharusnya di mobile app bisa ditampilkan/swipe? banyak gambar juga.
![image](https://user-images.githubusercontent.com/618412/78747187-f7ee5800-7992-11ea-97e8-dd72afd80d77.png)

Challengenya adalah fitur share-nya sih. Antara share per-image satu-satu atau bisa sekali share untuk banyak gambar. Silahkan pilih cara paling mudah.

**Comment by maasdi** [comment]
Kang @yohang88 belum ada asignee untuk issue ini kah? Saya tolong untuk update.

Untuk feature share-nya bisa multiple file share, karena share button-nya itu di listing page.

**Comment by yohang88** [comment]
Mas @maasdi sippo mas kayaknya belum ada yang ambil.
