### ISSUE TITLE
Menambahkan informasi hasil RDT

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-flutter#208]
Cek desain Figma http://bit.ly/Pikobar-Mobile

![image](https://user-images.githubusercontent.com/618412/79890671-0b390300-842a-11ea-8543-deb13baae3ab.png)
![image](https://user-images.githubusercontent.com/618412/79890696-11c77a80-842a-11ea-94ca-26a03abff4f4.png)

API yang bisa dipakai dari halaman https://pikobar.jabarprov.go.id/data

**Comment by jaluowen** [comment]
mas @yohang88  untuk `update terakhir`nya ambil dari api mana ya? solanya di api ini `https://covid19-public.digitalservice.id/api/v1/rekapitulasi/jabar` last updatenya `null`

**Comment by yohang88** [comment]
@jaluowen wait ini ada penyesuaian. Nampaknya jangan ambil data dari API, kita bridging biasa di firestore deh.
