### ISSUE TITLE
Pengurutan Video berdasarkan tgl entry

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-flutter#212]
Saran kalau pengurutan video berdasarkan tgl entry kira2 memungkinkan ga ya? kalau menggunakan sequence jika ada video baru harus diurutkan kembali semua videonya

**Comment by anandarh** [comment]
@adtrimurdani Memungkinkan mas, tinggal tambahkan field baru untuk tanggal entrynya.

**Comment by adtrimurdani** [comment]
ooh langsung aja di collection nya ya kang @anandarh ?

**Comment by anandarh** [comment]
@adtrimurdani Iya, coba tambahkan aja. Nanti di mobile di sesuaikan lagi.

**Comment by adtrimurdani** [comment]
siap @anandarh saya udah tambahkan field `published_at`, mungkin boleh di order by tgl publish yg terkini

**Comment by anandarh** [comment]
@adtrimurdani Oke siap.
