### ISSUE TITLE
Perubahan nomor Hotline Pikobar

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-flutter#214]
Dikarenakan WA Hotline Pikobar (yg ada di Nomor Darurat) ganti nomor lagi, maka ada perubahan skenario:
- Nomor tidak usah ditampilkan, tapi user bisa langsung klik button untuk mulai chat **<-- yang ini sudah done**
- Saat ini hotline pikobar itu berbentuk short url dikarenakan ada parameter utk mengirimkan template "welcome greeting" dulu secara otomatis ke WA nya, param tsb ada di url ini: https:/s.id/ChatbotPikobar

Kira2 memungkinkan ga ya url tsb dimasukkan ke remote config ini?
![image](https://user-images.githubusercontent.com/61811037/80786061-a1002b00-8bac-11ea-852c-a2683a4d3829.png)

**Comment by anandarh** [comment]
@adtrimurdani Kalau ditambahkan parameter pesan saja untuk mengisi templatenya gimana?

**Comment by adtrimurdani** [comment]
boleh kang @anandarh
