### ISSUE TITLE
Perubahan teks link "Selengkapnya" pada info RDT

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-flutter#215]
Yang "Selengkapnya" ini apakah bisa diganti dengan "Daftar RDT"? Karena user yang mendaftar RDT di atas 40 tahunan, takutnya ga terlalu ngeuh kalau teks link nya "Selengkapnya"
![image](https://user-images.githubusercontent.com/61811037/80787715-7a90be80-8bb1-11ea-8b53-3c62914b2611.png)

**Comment by gaganugraha33** [comment]
@adtrimurdani  bisa kang, berarti text Selengkapnya jadi dinamis ya?, bisa dirubah rubah?, mungkin harus dimasukin ke remote config juga biar dinamis

**Comment by adtrimurdani** [comment]
iya kang @gaganugraha33 untuk yg di halaman RDT aja. Atau kalau saat ini static, "Selengkapnya" bisa diubah ke "Daftar RDT" saja kang?

**Comment by gaganugraha33** [comment]
woh di menu RDT aja siap kang bisa @adtrimurdani
