### ISSUE TITLE
update deskripsi Pikobar di Play Store & App Store

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-flutter#219]
Berikut update deskripsi Pikobar untuk di-update di Play Store dan App Store (teks, gambar, dan video): [https://drive.google.com/drive/folders/1E62q4Jj70BWreaGj2eScat-tm71RXHaV](url)

**Comment by anandarh** [comment]
Play Store
- [ ] Teks
- [ ] Gambar
- [ ] Video

Note Play Store:
Video harus berupa link youtube.

App Store
- [ ] Teks
- [ ] Gambar
- [ ] Video

Note App Store:
Gambar harus dibuat dalam beberapa ukuran screen.
~ 5.5" (1242 x 2208 pixels)
~ 6.5" (1242 x 2688 pixels)
~ 12.9" (2048 x 2732 pixels)

**Comment by adtrimurdani** [comment]
siap, on progress utk item2 di atas kang @anandarh

**Comment by adtrimurdani** [comment]
kang @anandarh , ini link youtube video: [https://www.youtube.com/watch?v=Ataw_OYkqGo&feature=youtu.be](url)
