### ISSUE TITLE
Penambahan data PCR pada menu RDT

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-flutter#227]
Figma sedang dikerjakan oleh @ReksaMohammad dahulu

**Comment by yohang88** [comment]
Sip. Btw strateginya masih sama dengan yang lain ya, kalau bisa datanya diambil dari firestore, tidak langsung hit ke API Coredata.

**Comment by adtrimurdani** [comment]
figma updated yes, mangga dicek

**Comment by jaluowen** [comment]
Untuk data PCRnya berarti bikin document baru aja ya seperti RDT? @yohang88 @adtrimurdani

**Comment by yohang88** [comment]
@jaluowen iyes document baru aja, karena RDT ini beda dengan PCR (beda jenis test).
