### ISSUE TITLE
Action View PDF saat tap judul dokumen

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-flutter#233]
Saat ini aksinya adalah Download File. Sepertinya nice to have kalau aksinya adalah View Detail PDF saja daripada Download.

Sepertinya menarik:
https://pub.dev/packages/native_pdf_view

Kalau mau download/share, tetap bisa pakai menu share button (sudah ada).

**Comment by adtrimurdani** [comment]
Wah nice mas. Kalo saya coba sbg user, ketika mau share ke WA filenya di-download terlebih dahulu, jadi history sumber asli nya ga ada karena langsung share file
