### ISSUE TITLE
Feature Checkin Manual

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-flutter#234]
Saat ini background service masih diriset dan nampaknya masih ada kendala. https://github.com/jabardigitalservice/pikobar-flutter/issues/185

Meanwhile sampai OK, kita sediakan fitur manual Checkin dulu. Bayangan saya adalah di menu Profile, di bagian bawah menu Edit Profile/Akun, ditambahkan menu Check-in. Saat di-tap, masuk ke screen baru untuk checkin lokasi. Sekalian ditampilkan last checkinnya. Tombol Checkin manual.

Di database firestore, setiap action Checkin dilakukan insert baru:
`/users/userId/checkins/checkinId` dengan field checkin_at (Timestamp) dan checkin_location (Geopoint)

**Comment by adtrimurdani** [comment]
Kalau manual, masih perlu dibikin reminder ga ya utk check-in secara periodik mas @yohang88 ?

**Comment by yohang88** [comment]
Woke ini nampaknya diskusi lebih lanjut yak, karena nampaknya v1.5 ada kebutuhan segera rilis, jadi kita pending dulu aja.

**Comment by anandarh** [comment]
Gimana kalau untuk saat ini data lokasinya dikirim ke firestore tiap user buka app? Jadi ga perlu tap button / reminder lg.

**Comment by adtrimurdani** [comment]
yg kirim lokasi setiap buka app boleh sih kang @anandarh , biar bisa dites dulu utk tampilan datanya di dashboard contact tracing

**Comment by yohang88** [comment]
Terkait ide manual checkin, pindah ke sini yak https://github.com/jabardigitalservice/pikobar-flutter/issues/234

Yang update metode setiap buka app, bisa dibuat issue terpisah, karena itu juga sama-sama tracking, beda mekanisme aja.
