### ISSUE TITLE
Fitur Info Penting

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-flutter#235]
Konsepnya seperti Info Penting di Sapawarga. Yaitu menampilkan info/berita yang benar-benar di-highlight dan prioritas. Biasanya sangat penting.

![image](https://user-images.githubusercontent.com/618412/81617620-f4c20e00-940f-11ea-80ae-4b7965ae0597.png)

Cara kerjanya seperti Pikobar - Berita Terkini. Ada list di Home, Selengkapnya, dan View Detail.

Bikin firestore collection untuk `articles_important`.
![image](https://user-images.githubusercontent.com/618412/81649659-d9302500-945a-11ea-9958-fc4d251156d5.png)
- filter published `true`
- order by `published_at` descending
- ada action button di halaman detail (open webview biasa) + ditambahkan parameter URL UID, token seperti biasa

Nice to have ditambahkan action Push Notif untuk langsung jump ke Detail Info Penting.

**Comment by adtrimurdani** [comment]
Kalau misal info penting ini diambil dari berita jabar/nasional/dunia, memungkinkan ga kalau misal ditambahkan flag pada collection2 tsb dan nanti yg ter-flag akan muncul sbg info penting juga? cc mas @yohang88 @gaganugraha33

**Comment by yohang88** [comment]
Sebaiknya beda mas. Biasanya Info Penting di Sapawarga itu yang actionable, ada aksi yang bisa diikuti oleh user. Misal isi survei, download, dsb.
