### ISSUE TITLE
Menyesuaikan urutan menu utama di Home Screen

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-flutter#24]
Cek desain terbaru dan fokus ke urutan menu utama https://bit.ly/Pikobar-Mobile

- Fitur yang masih development (Dalam Proses) dipindah ke Menu Lainnya.
- Jabar Saber Hoax dipindahkan dari Menu Lainnya ke depan
- Informasi Dunia dipindahkan dari Menu Lainnya ke depan

**Comment by anandarh** [comment]
Done
