### ISSUE TITLE
Penambahan menu Daftar Penerima Bansos yang webview ke websitenya

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-flutter#248]
![image](https://user-images.githubusercontent.com/61811037/81895832-6307fb80-95dd-11ea-8d51-89b8ea91d689.png)
Webview ke: https://bansos.pikobar.jabarprov.go.id/
Tapi di-disable dulu di remote confignya, ya.

**Comment by yohang88** [comment]
Woke sip.

@tim mobdev, sekalian aja dibuat remote config untuk:
1. Gambar (orang bawa paket), pastikan gambarnya network cached kalau bisa
2. Caption "Daftar Penerima Bantuan Sosial bagi blablabla"
3. Action open URL (standar + query param UID, token, dsb)
5. Show/Hide banner

Cek contoh remote config.

**Comment by jaluowen** [comment]
@yohang88 mas kira2 nama remote confignya apa ya? soalnya kan array bisa saja isinya tidak hanya untuk daftar penerima bansos

**Comment by yohang88** [comment]
@jaluowen kalau `group_home_bigbanner" gimana? :)))

**Comment by jaluowen** [comment]
boleh mas cukup general sepertinya :) @yohang88
