### ISSUE TITLE
Feature: Force Update

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-flutter#25]
Mobile app akan cek ke backend Firebase (firestore / remote config?) dan melakukan komparasi versi aplikasi terhadap versi di backend. Jika ada flag force update, maka akan muncul popup di home screen untuk melakukan Update.

**Comment by aldidoanta** [comment]
Referensi: [Firebase Remote Config](https://firebase.google.com/docs/remote-config/)

Aku baca-baca dulu

**Comment by alchemistt99** [comment]
https://pub.dev/packages/firebase_remote_config

package nya

**Comment by alchemistt99** [comment]
saya izin buat parameter baru :
1. force_update_required
2. force_update_current_version
3. force_update_store_url

@yohang88 @aldidoanta
