### ISSUE TITLE
Menyesuaikan bagian Live Update di Home Screen

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-flutter#26]
Cek desain terbaru dan fokus ke bagian widget terkait Berita https://bit.ly/Pikobar-Mobile

Dibuat jadi 3 tab:
1. Berita Terkini -> Jabar (pers release) diambil dari collection `articles`
2. Nasional -> diambil dari collection `news` (belum ada)
3. Dunia -> diambil dari collection `latest_updates`

Semua content akan diisi dari backend manual dulu.

**Comment by aldidoanta** [comment]
@yohang88 @gaganugraha33  Untuk penamaan collection di firebase, kita sekalian perbaiki aja ya.
Misalnya:

- Berita Terkini: `articles` (nggak perlu diubah karena datanya sudah dipakai sama PWA)
- Nasional: `articles_national`
- Dunia: `articles_world` atau `articles_global`

Ada usulan untuk penamaan?

**Comment by yohang88** [comment]
@aldidoanta sangat boleh, dibantu komunikasikan ke mobile & app yes agar data sourcenya sama 😁

**Comment by aldidoanta** [comment]
Kang @gaganugraha33 aku update ya penamaan collection di firebase. Struktur 3 collection tsb akan sama semua

**Comment by aldidoanta** [comment]
> @yohang88 @gaganugraha33 Untuk penamaan collection di firebase, kita sekalian perbaiki aja ya.
> Misalnya:
> 
> * Berita Terkini: `articles` (nggak perlu diubah karena datanya sudah dipakai sama PWA)
> * Nasional: `articles_national`
> * Dunia: `articles_world`
> 
> Ada usulan untuk penamaan?

@gaganugraha33 Firebase collectionya sudah ada ya. untuk `articles_world` masih pakai berita nasional

**Comment by gaganugraha33** [comment]
oke siapp nuhunn @aldidoanta otw sesuain

**Comment by aldidoanta** [comment]
Oke, data awal untuk `articles_national` dan `articles_world` udah masuk ya.
Untuk persoalan apakah butuh CRM untuk ini, nanti bisa dibahas setelah revisi hari ini rilis.

**Comment by gaganugraha33** [comment]
done & sudah di merge
