### ISSUE TITLE
Menu-Feature yang menggunakan Webview, URL dan Caption-nya menggunakan Firebase Remote Config

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-flutter#33]
Untuk feature & menu yang pakai embed web, URL dan Caption menunya diubah menggunakan Firebase Remote Config.

Cek desain terbaru.

**Comment by yohang88** [comment]
@anandarh kalau bisa selain URL, caption menu-nya juga ambil dari firebase config yes

**Comment by anandarh** [comment]
#42 Done
