### ISSUE TITLE
apakah ada trello / slack untuk media komunikasi?

### ISSUE THREAD

**Issue by IhwanID** [jabardigitalservice/pikobar-flutter#52]
Halo akang akang, saya ingin ikut berkontribusi. apakah ada media untuk berkomunikasi terkait apa saja feature / bug yang akan di kerjakan. 
nuhun

**Comment by aldidoanta** [comment]
Halo kang, terima kasih atas minatnya untuk berkontribusi.

Saat ini belum ditentukan apakah akan ada project management tools dan communication tools yang dapat digunakan untuk publik (selain GitHub).

Sesuai dengan [panduan umum kontributor](https://github.com/jabardigitalservice/pikobar-relawan-readme), akang bisa mendaftarkan diri dulu [di sini](https://relawancovid19.id/j/pikobar-flutter-developer). Jika ada ide dan usulan terkait fitur, dapat ditulis di [formulir berikut](http://bit.ly/UsulanPikobar).

Hatur nuhun :pray:
