### ISSUE TITLE
Menambahkan screen My Account dan implementasi Google Sign In

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-flutter#55]
Menambahkan screen baru My Account (tambah menu di navigasi bawah).

Jika belum login, tampilkan tombol Sign In with Google (pakai firebase). Jika sudah login, tampilkan foto profil dan nama pengguna serta tombol untuk Log Out.

Pastikan user identity ini bisa diakses di screen-screen lainnya yang mengharuskan login.

Edit:
Diimplementasikan di menu Survei ya. Sebelum masuk ke halaman daftar Survei, user harus login terlebih dahulu.

**Comment by yohang88** [comment]
Ini bagaimana? jika sudah, jangan dimerge dulu yes.

**Comment by jaluowen** [comment]
Udah beres mas, siap di close merge dulu @yohang88

**Comment by yohang88** [comment]
Minta pendapat dong @anandarh @alchemistt99 @gaganugraha33 progress hasilnya seperti apa yes.

**Comment by aldidoanta** [comment]
Oiya, maaf saya kelewat issue yang ini.
Fitur apa saja yang butuh sign in? Apakah hanya `Logistik`, atau ada fitur lain yang perlu sign in?

**Comment by aldidoanta** [comment]
Menyambung ke issue https://github.com/jabardigitalservice/pikobar-flutter/issues/62, apakah bisa diasumsikan, saat ini semua pesan broadcast sifatnya publik dan dapat diakses tanpa perlu log in?

Kalau pesan broadcast sifatnya publik, supaya URL-nya dapat dimasukkan untuk keperluan share pesan broadcast.

**Comment by yohang88** [comment]
Untuk saat ini percobaan untuk menu Survei ya. Jadi sebelum mengisi perlu Login dulu.

@aldidoanta Pesan kita arahkan publik aja kali ya, nanti kalau minta bisa targeting wilayah, kebayang ribet lagi hahaha 😂

**Comment by yohang88** [comment]
@aldidoanta @alchemistt99 @anandarh @gaganugraha33 @jaluowen minta pendapat, apakah kita perlu record di firestore juga untuk setiap user yang login, kalau di groupware seperti ini:

![image](https://user-images.githubusercontent.com/618412/77317702-3e5e7880-6d3e-11ea-948b-1a1b15717a8c.png)

Tantangannya ini terkait Role sih. By default Firebase Authentication ga ada Role-nya. Jadi harus define database untuk user + rolenya. Atau ada pendekatan lain?
