### ISSUE TITLE
Development dan build platform iOS

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-flutter#57]
Dicoba dikembangkan agar bisa dipakai pada platform iOS.

**Comment by anandarh** [comment]
Di emulator ini sudah aman, tinggal coba test di real device. @yohang88

**Comment by alchemistt99** [comment]
tinggal akun ios devepelover :laughing: @yohang88

**Comment by anandarh** [comment]
- [ ] Versi 1.1.2

- [ ] Versi 1.2.0

- [ ] Publish to App Store
