### ISSUE TITLE
Share berita dan pesan ke aplikasi lain (Whatsapp, dsb)

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-flutter#58]
Pada halaman detail berita (Jabar, Nasional, Dunia) dan detail Pesan, ditambahkan action button untuk Share. Saat di-tap, akan muncul pilihan share ke aplikasi lain (standard seperti Android pada umumnya). Yang di-share adalah judul berita + link download app Play Store, contoh:

```
Jabar Akan Gelar Rapid Test COVID-19 secara Massal di Sejumlah Daerah

Baca selengkapnya di aplikasi Pikobar:
https://play.google.com/store/apps/details?id=id.go.jabarprov.pikobar
```

Catatan: better kalau bisa ada potongan detail berita yang dimasukkan di atas, namun hati-hati dengan limitasi jumlah karakter yang diizinkan.

**Comment by aldidoanta** [comment]
Sepertinya bisa sekalian share URL berita yang ada di Pikobar Web mas.

**Comment by yohang88** [comment]
> Sepertinya bisa sekalian share URL berita yang ada di Pikobar Web mas.

Kalau bisa, better sih @aldidoanta. Tapi berarti di database perlu properti menyimpan public URL web ya?

**Comment by alchemistt99** [comment]
@gaganugraha33  jangan lupa set event analytics nya

**Comment by gaganugraha33** [comment]
oke siap mangg @alchemistt99 , klo yg ini format sharenya title + link playstore aja?, atau link url beritanya di share juga? @aldidoanta @yohang88

**Comment by aldidoanta** [comment]
@gaganugraha33 Iya, share link playstore dan URL beritanya juga kang (yang dari pikobar web)

**Comment by aldidoanta** [comment]
Oiya @gaganugraha33 Saat ini untuk web, hanya `Berita Jabar` yang punya public URL. Kalau `Berita Nasional` dan `Berita Dunia` belum punya public URL, cc @adrianpdm 

Sebaiknya behaviornya disamakan, tapi artinya harus nambah routing baru. Ada usulan kang @adrianpdm ?
