### ISSUE TITLE
API Berita Jabar

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-flutter#61]
Berikut API untuk berita Jabar yang sumbernya dari Humas Jabar:
http://humas.jabarprov.go.id/api/berita/jabar-tanggap

**Comment by yohang88** [comment]
Ini untuk apa ya? Usul saya kita ga pakai API dari sini, tetap pakai Firebase:
- Contentnya bisa jadi tidak curated sesuai topik Pikobar
- Tidak yakin infrastruktur servernya bisa handle request massif
