### ISSUE TITLE
Push notifications akan masuk ke screen yang sesuai saat di-tap

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-flutter#62]
Saat ini Push Notification yang di-create dari Firebase Console > Cloud Messaging, saat di-tap oleh User, akan masuk ke Home Screen. Bagaimana caranya agar:

1. Jika tipenya Berita Jabar/Nasional, masuk ke screen detail berita Jabar/Narsional.
2. Jika tipenya Pesan, masuk ke screen detail Pesan.

Apa parameter yang harus ditambahkan saat create di Firebase Console? Bagaimana agar apps bisa melanjutkan aksi sesuai tipenya masing-masing?

**Comment by aldidoanta** [comment]
@yohang88 Untuk issue yang ini, asumsinya link-nya hanya ke bagian internal di app, atau sekalian bisa external URL seperti Sapawarga?

**Comment by anandarh** [comment]
Setup untuk mengirim push notification Berita & Pesan dari firebase console.

`topic : general`
`Android Notification Channel: pikobar_channel_id`

_custom data:_
`click_action: FCM_PLUGIN_ACTIVITY`
`target: broadcast / news ` 
`type: articles / articles_national / articles_world` -> hanya untuk news.
`id: <Document ID>`

<img width="942" alt="Screen Shot 2020-03-23 at 22 07 23" src="https://user-images.githubusercontent.com/26994065/77332378-97d1a200-6d54-11ea-8457-4be9d3e707eb.png">

<img width="942" alt="Screen Shot 2020-03-23 at 22 21 58" src="https://user-images.githubusercontent.com/26994065/77332564-c8194080-6d54-11ea-90ea-ebac60147d61.png">
