### ISSUE TITLE
Mengupdate README dan Wiki

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-flutter#63]
Agar tim dan relawan bisa contribute, perlu dokumentasi yang jelas.

- [x] Update README untuk step-by-step installation di local machine

- [x] Membuat repository wiki yang berisi:
    - Software Architecture
    - Struktur Collection di Firestore

**Comment by aldidoanta** [comment]
Related https://github.com/jabardigitalservice/pikobar-jabarprov-go-id/issues/7

**Comment by aldidoanta** [comment]
Progress saat ini: menjelaskan overview service yang digunakan di Firebase, seperti Firestore, Storage, dan Remote Config

WIP struktur collection di Firestore

**Comment by aldidoanta** [comment]
Mas @yohang88 Untuk wiki, analytics events perlu dimasukkan juga nggak? Atau struktur databasenya dulu aja yang dijelaskan?

**Comment by aldidoanta** [comment]
@jabardigitalservice/pikobar [struktur awal untuk Wiki](https://github.com/jabardigitalservice/pikobar-flutter/wiki) sudah dibuat ya. Issue saat ini: tidak ada wiki untuk multiple repository. Belum tau apakah sebaiknya bikin satu repo untuk documentation Pikobar, atau bikin satu wiki untuk tiap repo. Silakan kalau ada masukan.

**Comment by aldidoanta** [comment]
@jaluowen @alchemistt99 @anandarh Nanti kalau development sudah cukup lowong, boleh minta tolong untuk Update README ya, isinya step-by-step installation di local machine.

**Comment by anandarh** [comment]
@aldidoanta Saya update CONTRIBUTING nya dikit yes.

**Comment by aldidoanta** [comment]
@anandarh Siap kang, boleh dilengkapi dengan branching strategy dan workflow di internal tim

**Comment by leotj** [comment]
Hi tim jabardigitalservice
Apakah prioritas issue ini bisa dinaikkan lagi?
Terutama untuk setting up local development.

**Comment by leotj** [comment]
> @jaluowen @alchemistt99 @anandarh Nanti kalau development sudah cukup lowong, boleh minta tolong untuk Update README ya, isinya step-by-step installation di local machine.

Hi tim jabardigitalservice
Apakah prioritas issue ini bisa dinaikkan lagi?
Terutama untuk setting up local development.

**Comment by aldidoanta** [comment]
> Hi tim jabardigitalservice
> Apakah prioritas issue ini bisa dinaikkan lagi?
> Terutama untuk setting up local development.

Up @alchemistt99 :grin:

**Comment by TendiF** [comment]
ada satu file yg harus ada ketika pertama pull lalu run  
![image](https://user-images.githubusercontent.com/19442589/78466891-f7ef1d80-7730-11ea-816f-df658a34e6e3.png)
cuman karena di .gitignore yg baru masuk cukup kesulitan untuk install di local machine

**Comment by aldidoanta** [comment]
Siap kang @TendiF, nanti bisa saya tambahkan untuk README.

Related https://github.com/jabardigitalservice/pikobar-flutter/issues/161, untuk kebutuhan local development.
