### ISSUE TITLE
upgrade minimum sdk

### ISSUE THREAD

**Issue by alifgiant** [jabardigitalservice/pikobar-flutter#77]
Apa mungkin SDK nya di upgrade?

https://github.com/jabardigitalservice/pikobar-flutter/blob/e18928cd969ff2b6b6ebae558315c488da87953e/pubspec.yaml#L17

![image](https://user-images.githubusercontent.com/6872500/77393890-a067be00-6dd0-11ea-895f-5bc0aef8a84d.png)

benefit:
- Extention function
- inline conditional rendering in list
- better generic

ref:
https://medium.com/dartlang/dart-2-7-a3710ec54e97
https://9to5google.com/2019/11/05/dart-2-6-released/
https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md

**Comment by alchemistt99** [comment]
@alifgiant silahkan saja di upgrade :+1:
