### ISSUE TITLE
Persentase ODP dan PDP ditambahkan text "...% dari Total"

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-flutter#86]

**Comment by gaganugraha33** [comment]
ini presentase prosesnya ya kang?, sama kaya di web? @adtrimurdani

**Comment by adtrimurdani** [comment]
iya betul kang @gaganugraha33 . Karena di App untuk angka Total dan Selesai tidak ditampilkan, maka text `%` ditambahkan aja jadi `% dari Total` (co:/ 64.66% dari Total)

**Comment by gaganugraha33** [comment]
![photo_2020-03-25_13-58-51](https://user-images.githubusercontent.com/17392476/77510491-85b14a00-6ea1-11ea-9f6f-4deec55e9770.jpg) jadi seperti ini kah mas? @adtrimurdani , ini berdasarkan desain figma kemarin

**Comment by adtrimurdani** [comment]
Ouw % ini dari figma ya, my bad saya ga ngecek lagi, hehe.
Iya kang ditambah jadi `xx.xx% dari Total`

Tapi, kalau text jadi kepanjangan (turun ke bawah), lebih baik hanya angka aja yang ditampilkan, kang

**Comment by gaganugraha33** [comment]
oke kang ini udah done ya @adtrimurdani
