### ISSUE TITLE
Home Announcement

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-flutter#89]
Nampaknya kita perlu buat announcement/alert dengan tampilan seperti ini. Jadi alternatif dari Banner. Bisa ditampilkan saat kondisi-kondisi tertentu yang urgent. Karena kalau banner, dia scrolling takutnya user tidak mengikuti.

![image](https://user-images.githubusercontent.com/618412/77503987-a4a7e000-6e91-11ea-8d54-70ea78e98ef7.png)

*Akan menggunakan Firebase remote configurable.

Open discussion, cc: mas @adtrimurdani

**Comment by yohang88** [comment]
Ditambahkan saat di-tap, masuk ke Webview. Lihat Firebase Remote Config, `announcement > action_url`

@gaganugraha33

**Comment by gaganugraha33** [comment]
@yohang88 announcement bakal muncul klo `enabled:true`mas?,  klo Selengkapnya di tap ambil dari `action_url`, klo text "Temukan informasi tebaru Covid" itu ngambilnya dari `content` mas?

**Comment by yohang88** [comment]
@gaganugraha33 betul.
