### ISSUE TITLE
Tab Berita Nasional blank

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-flutter#90]
Takutnya ada format isian yang salah ketika input article, jadi saya delete dulu. Tapi setelah didelete halaman tetap blank

**Comment by aldidoanta** [comment]
Iya kang, ada `published_at` yang berubah jadi string, bukan timestamp.
Penyebabnya, pushtable.com menganggap time timestamp sebagai string. Saya fix manual dulu

Nanti saya coba workaroundnya gimana

**Comment by adtrimurdani** [comment]
siap kang @aldidoanta nuhuns

**Comment by aldidoanta** [comment]
@adtrimurdani  Untuk workaroud-nya saya tulis di sini ya kang.
https://gist.github.com/aldidoanta/33b2c7ee5552a8605eb079870b91513e

Kekurangannya, timestamp-nya jadi otomatis, berdasarkan kapan kita bikin datanya di Firebase. Kalau mau diganti supaya cocok dengan waktu rilis berita, timestamp masih harus di-edit manual di Firebase.

Tapi kalau Kang Adit nggak ada kebutuhan untuk edit timestamp, berarti workaround di atas bisa dilakukan ya kang.

**Comment by adtrimurdani** [comment]
Saya sudah coba kang, ga masalah di edit timestamp di firebase, ini udah cukup membantu.
Case closed, ya. Thanks kang @aldidoanta
